# BAKGRUND - med anime wallpaper på båda skärmarna
background {
    monitor =
    path = /home/fling/Pictures/Wallpapers/animepurple.png
    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.6
    vibrancy = 0.3
    vibrancy_darkness = 0.4
}

# KLOCKA - Stor och dominerende, Catppuccin Mauve
label {
    monitor = DP-2
    text = $TIME
    color = rgba(cba6f7ee)
    font_size = 130
    font_family = JetBrainsMono Nerd Font ExtraBold
    shadow_passes = 3
    shadow_size = 10
    shadow_color = rgba(17001aaa)
    shadow_boost = 1.5
    position = 0, 180
    halign = center
    valign = center
}

# DATUM - Under klockan
label {
    monitor = DP-2
    text = cmd[update:60000] date "+%A, %d %B"
    color = rgba(b4befe99)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    shadow_passes = 2
    shadow_size = 5
    shadow_color = rgba(17001aaa)
    position = 0, 95
    halign = center
    valign = center
}

# "WELCOME BACK" - Med Catppuccin Lavender
label {
    monitor = DP-2
    text =  fling
    color = rgba(cdd6f4dd)
    font_size = 22
    font_family = JetBrainsMono Nerd Font Bold
    shadow_passes = 2
    shadow_size = 6
    shadow_color = rgba(17001aaa)
    position = 0, 30
    halign = center
    valign = center
}

# INPUT-FÄLT - Pill-shape med Mauve/Flamingo gradient
input-field {
    monitor = DP-2
    size = 280, 58
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.25
    dots_center = true
    dots_rounding = -1
    inner_color = rgba(18131fcc)
    outer_color = rgba(cba6f7cc) rgba(f5c2e7cc) 45deg
    font_color = rgba(cdd6f4ff)
    check_color = rgba(94e2d5ff) rgba(89dcebff) 120deg
    fail_color = rgba(f38ba8ff) rgba(eba0acff) 40deg
    capslock_color = rgba(f9e2afff)
    numlock_color = rgba(cba6f7ff)
    bothlock_color = rgba(fab387ff)
    rounding = 29
    fade_on_empty = false
    fade_timeout = 2000
    placeholder_text = <span foreground="##a6adc8" font_family="JetBrainsMono Nerd Font"> Password...</span>
    hide_input = false
    position = 0, -50
    halign = center
    valign = center
    fail_text = <span foreground="##f38ba8">$FAIL</span>
    shadow_passes = 2
    shadow_size = 8
    shadow_color = rgba(17001aaa)
}

# SYSTEMINFORMATION - Nere till vänster
label {
    monitor = DP-2
    text = cmd[update:1000]  $FPWM  |  $KBD
    color = rgba(a6adc8aa)
    font_size = 12
    font_family = JetBrainsMono Nerd Font
    position = 30, -30
    halign = left
    valign = bottom
}
