general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on DP-2 && hyprctl dispatch dpms on HDMI-A-1
}

# 5 min - lås med hyprlock
listener {
    timeout = 300
    on-timeout = loginctl lock-session
    on-resume = hyprctl dispatch dpms on DP-2 && hyprctl dispatch dpms on HDMI-A-1
}

# 20 min - släck skärmarna
listener {
    timeout = 1200
    on-timeout = hyprctl dispatch dpms off DP-2 && hyprctl dispatch dpms off HDMI-A-1
    on-resume = hyprctl dispatch dpms on DP-2 && hyprctl dispatch dpms on HDMI-A-1
}

# 2h - sleep/suspend
listener {
    timeout = 7200
    on-timeout = systemctl suspend
}
