#################
### AUTOSTART ###
#################

exec-once = hyprpanel & hyprpaper &
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = systemctl --user start xdg-desktop-portal-hyprland
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = openrgb --profile main.orp --startminimized
exec-once = systemctl --user start xdg-desktop-portal-gtk
exec-once = hyprswitch init --show-title &
exec-once = rm -f ~/.local/share/cliphist/db && wl-paste --type text --watch cliphist store & wl-paste --type image --watch cliphist store

exec-once = kitty --title peaclock -e peaclock
exec-once = kitty --title sysinfo -e sh -c "fastfetch; fish"
exec-once = kitty --title btop -e btop
exec-once = kitty --title cava -e cava
exec-once = hypridle
