#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 2
    gaps_out = 10
    border_size = 1          # Nu sänkt till en tunn, diskret linje
    col.active_border = rgba(c4a8ffee) rgba(bf5cbfee) rgba(ff00ffee) rgba(7c5cbfee) 270deg
    col.inactive_border = rgba(3a384800) 
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 10
    rounding_power = 2
    active_opacity = 1.0
    inactive_opacity = 0.95  # Detta gör att appar i bakgrunden blir lite genomskinliga

    shadow {
        enabled = true
        range = 15             
        render_power = 3
        color = rgba(c4a8ffcc) 
        color_inactive = rgba(1a1a1a66)  
    }

    blur {
        enabled = true
        size = 3
        passes = 1
        vibrancy = 0.1696
    }
}

# --- WINDOW RULES ---
# Denna regel gör att Brave alltid är 100% solid, även när du inte klickat på det
windowrule {
    name = brave-opacity
    match:class = ^(brave-browser)$
    opacity = 1.0 override 1.0 override
}

animations {
    enabled = yes
    bezier = ease, 0.25, 0.1, 0.25, 1.0
    bezier = overshot, 0.13, 0.99, 0.29, 1.05
    bezier = smoothSlide, 0.95, 0, 0.05, 1

    animation = windows, 1, 5, overshot, gnomed
    animation = windowsOut, 1, 5, ease, slide bottom
    animation = windowsMove, 1, 5, overshot, slide
    animation = layers, 1, 5, ease, gnomed
    animation = fade, 1, 3, ease
    animation = border, 1, 2, ease
    animation = workspaces, 1, 3, ease, slidefade
} 

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
}
