################
### MONITORS ###
################
# Sekundär AOC 1080p till vänster
monitor=HDMI-A-1,1920x1080@144,0x0,1

# Primär Samsung Odyssey 1440p till höger
monitor=DP-2,2560x1440@165,1920x0,1
