##############################
### WINDOWS AND WORKSPACES ###
##############################

layerrule = blur on, match:namespace quickshell
layerrule = ignore_alpha 0.5, match:namespace quickshell

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

# File picker popup
windowrule {
    name = filepicker-float
    match:class = ^xdg-desktop-portal-gtk$
    float = yes
    size = 900 600
    center = yes
}


# Dashboard workspace windows
windowrule {
    name = peaclock-layout
    match:title = ^peaclock
    float = yes
    move = 10 57
    size = 1168 896
    workspace = 1
}
windowrule {
    name = sysinfo-layout
    match:title = ^sysinfo$
    float = yes
    move = 10 955
    size = 1168 475
    workspace = 1
}
windowrule {
    name = btop-layout
    match:title = ^btop
    float = yes
    move = 1180 57
    size = 1370 700
    workspace = 1
}
windowrule {
    name = cava-layout
    match:title = ^cava$
    float = yes
    move = 1180 759
    size = 1370 671
    workspace = 1
}

# Floating by default
windowrule {
    name = popsicle-float
    match:class = ^AppRun\.wrapped$
    match:title = ^Popsicle$
    float = yes
    center = yes
}
windowrule {
    name = gnome-calculator-float
    match:class = ^org\.gnome\.Calculator$
    float = yes
    center = yes
}
windowrule {
    name = pavucontroll
    match:class = ^org.pulseaudio.pavucontrol
    float = yes
    center = yes
    size = 800 700
}
windowrule {
    name = blueman-manager
    match:class = ^blueman-manager
    float = yes
    center = yes
    size = 800 700
}
windowrule {
    name = nmtui
    match:class = ^wifibt
    float = yes
    center = yes
    size = 800 700
}
